### ISSUE TITLE
Update to LLVM 8.0

### ISSUE THREAD

**Issue by feliwir** [microsoft/LLVMSharp#84] opened 2018-11-25 18:19 UTC
Hello everyone,

by now LLVM 7.0 is released and LLVM 8.0 is already in development. Are there any plans to update in the near future?

**Comment by mjsabby** [comment] 2018-11-25 23:32
@TChatzigiannakis any updates on your API work? I can continue the LLVM 7 migration and you can fix up any new APIs?

**Comment by TChatzigiannakis** [comment] 2018-11-26 09:31
@mjsabby I am at a conference these days. I'll probably find a few hours one of these afternoons to amend it.

**Comment by Axiverse** [comment] 2019-01-15 02:18
This would be greatly appreciated!

**Comment by sladage** [comment] 2019-03-22 14:35
Might as well update straight to LLVM 8.0 at this point.

**Comment by cloudrex** [comment] 2019-04-12 13:13
Yes, this would be great!

**Comment by mjsabby** [comment] 2019-04-12 15:42
I've setup continuous integration of Windows LLVM here, https://dev.azure.com/llvmsharp/llvm/_build?definitionId=5.

The problem is updating the C# code as well. I'll skip 7.0 and move to 8.0

**Comment by tannergooding** [comment] 2019-04-30 01:18
The raw P/Invokes have now been updated to 8.0. There is still quite a bit of work to add object-oriented wrappers for the new APIs however.

**Comment by cloudrex** [comment] 2019-04-30 01:42
> The raw P/Invokes have now been updated to 8.0. There is still quite a bit of work to add object-oriented wrappers for the new APIs however.

I didn't even know the API wrappers existed until recently, and have been working with the raw API lol. So, are the "raw" APIs complete?

**Comment by tannergooding** [comment] 2019-04-30 01:55
Yes, as far as I am aware. If they aren't feel free to ping me and I'll work on fixing any issues 😄

**Comment by yowl** [comment] 2019-04-30 23:08
If anyone can help me with building the `libllvm.dll`, specifically where to find/build `MergeLLVM.lib` for v8.0.0 I'd appreciate it, thanks.

**Comment by mjsabby** [comment] 2019-04-30 23:12
@yowl you can look at the build definitions for libLLVM.dll here

https://dev.azure.com/llvmsharp/llvm/_build?definitionId=4
https://dev.azure.com/llvmsharp/llvm/_build?definitionId=1

Let me know if you can't access it.

**Comment by yowl** [comment] 2019-04-30 23:25
Thanks, I see the artifacts have what I needed so that's enough for me.

**Comment by mnxn** [comment] 2019-05-02 15:10
Will this be published to NuGet soon?

**Comment by tannergooding** [comment] 2019-05-02 15:23
I think, if it was pushed to NuGet (or an alternative like MyGet), it would be better as a preview for right now.

That would allow people to consume it easily and provide feedback that things are working correctly.

**Comment by mjsabby** [comment] 2019-05-02 16:00
Yup, I'll put it up as LLVMSharp 8.0-beta1 or something. @tannergooding it would be nice to see if CoreRT still works with the WASM stuff.

**Comment by yowl** [comment] 2019-05-02 16:02
Happy to try corert+wasm.  Was going to try now with the devops artifacts, but if the nuget is incoming I'll wait

**Comment by mjsabby** [comment] 2019-05-02 18:52
well it'd be great if you could try it :)

**Comment by yowl** [comment] 2019-05-02 19:22
Sure, but you'll have to answer my noobie question first.  libLLVM.dll,  in the artifacts this is present and is  174KB.  I currently have from a nuget reference `<Content Include="..\..\..\packages\libllvm\6.0.0-beta1\runtimes\win-x64\native\libLLVM.dll"` which is around 41MB, so clearly these are not the same.  Am I meant to build libLLVM to create a library that links in `MergeLLVM.lib` if so how?

**Comment by yowl** [comment] 2019-05-03 02:23
Doing the compilation against LLVMSharp.dll (and ignoring the libllvm.dll for now).  I notice that when passing a stringRef ,e.g `CreateCompileUnit` http://llvm.org/doxygen/classllvm_1_1DIBuilder.html#a7b242bb279f52ed3f95e616abdad3839, param `Producer` the length parameter is of type `IntPtr` which seems a bit odd, but not a big deal, I just need to cast, i.e.
```
                    LLVMMetadataRef compileUnitMetadata = LLVM.DIBuilderCreateCompileUnit(_compilation.DIBuilder, LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC,
                        fileMetadata, "ILC", (IntPtr)3, isOptimized: false, String.Empty, (IntPtr)0, 1, String.Empty, (IntPtr)0, LLVMDWARFEmissionKind.LLVMDWARFEmissionFull, 0, false, false);
```

**Comment by mjsabby** [comment] 2019-05-03 04:09
@yowl I botched up something .. will look. Possibly the exports file generation.

**Comment by yowl** [comment] 2019-05-06 00:29
I can compile, but at run time it looks for `llvm-c.dll` which I dont seem to have in my llvm installation.

**Comment by yowl** [comment] 2019-05-09 12:52
> https://dev.azure.com/llvmsharp/llvm/_build?definitionId=4
> https://dev.azure.com/llvmsharp/llvm/_build?definitionId=1
> 
> Let me know if you can't access it.

@mjsabby  I can see the ouput but not the yaml, so can't see how it is adding nor generating `llvm-c.dll` as that appears to be added as an import library not a static library.  I built llvm locally but dont have that dll, confused...

**Comment by ericsink** [comment] 2019-05-29 19:19
Just to verify, nobody has gotten a working libLLVM.dll for 8.0 yet, right?  

I've been trying to either find or build this DLL, but it looks like we're not there yet.

**Comment by tannergooding** [comment] 2019-05-29 19:50
@ericsink, you can download the prebuilt binaries from http://releases.llvm.org/download.html#8.0.0

**Comment by mnxn** [comment] 2019-05-29 19:57
no libLLVM.dll there
the windows llvm builds are missing a lot of libraries and tools

**Comment by ericsink** [comment] 2019-05-29 19:59
@tannergooding Whoa -- do the prebuilt releases contain libLLVM.dll ?  I'm referring to the single big libLLVM shared library, for Windows, suitable for attempting to use with LLVMSharp.  

I've seen indications that for Windows, building libLLVM.dll is not supported by the main LLVM build system.  And my attempts confirm this.

NuGet has one, but it's version 7.0.

I've seen efforts in that direction here from @mjsabby and @kodraus, but no evidence of success yet.

**Comment by yowl** [comment] 2019-05-29 20:52
On Windows, I built llvm 9 (top of tree), used the v8 interop llvmsharp dll from the builds linked above and compiled a corert program with it.  However have not been able to actually run it due to a problem with wasm-ld https://bugs.llvm.org/show_bug.cgi?id=41717

**Comment by tannergooding** [comment] 2019-05-29 20:52
> no libLLVM.dll there

Ah, right. I had manually patched my install after I built locally, which is why it's in my install folder 🤦‍♂ 

Let me see if I can get it built locally again and I'll share out once completed or update if it fails.

**Comment by tannergooding** [comment] 2019-05-29 22:25
Ok, I got everything working at least from the perspective that you can generate a DLL that is usable for `LLVMSharp`: 
[LLVM-C.zip](https://github.com/microsoft/LLVMSharp/files/3234682/LLVM-C.zip)

**Comment by tannergooding** [comment] 2019-05-29 22:25
Namely, when you build LLVM the `libllvm` dynamic library is not built by default and you must turn on `LLVM_BUILD_LLVM_DYLIB`. However, that particularly setting does not currently work for MSVC.

However, on Windows, there is the `LLVM_BUILD_LLVM_C_DYLIB` option instead. That option defaults to off in `release_80` but was recently changed to default to on in `master`.

If you follow the normal directions for building LLVM on Windows (https://releases.llvm.org/8.0.0/docs/CMake.html) and ensure that `LLVM_BUILD_LLVM_C_DYLIB` is on, you will get a `LLVM-C.dll` library in your output folder. This is effectively `libllvm.dll` but with only the exported C APIs available (which are all that are consumed from LLVMSharp anyways).

If you want the full `libllvm.dll`, with exported C++ functions, you have to configure CMake to build using clang or gcc instead (which often involves a lot more setup and sometimes additional GNU tools or a GNU host environment).

**Comment by tannergooding** [comment] 2019-05-29 22:27
For reference, the zip I attached above was the `Release` build for https://github.com/llvm-mirror/llvm/commit/d519e424c503d2d2a723284664a509a6cd5401a8, which is the current head of https://github.com/llvm-mirror/llvm/tree/release_80.

It was built using Visual Studio 2019 version 16.2 Preview 1

**Comment by ericsink** [comment] 2019-05-29 22:55
Hmmph.  I guess I was making this harder than it needed to be.

I had gone through similar steps and ended up getting `LLVM-C.dll`, but when I compared it to `libLLVM.dll` from the nuget pkg and saw that it (1) had a different name, and (2) was much smaller , I assumed it couldn't work.

I'll give it a try.  Thanks.

**Comment by ericsink** [comment] 2019-05-30 19:38
FWIW update:

The LLVM-C.dll posted by @tannergooding is working fine for me with LLVMSharp.

**Comment by tannergooding** [comment] 2019-05-30 19:57
It's worth noting that I talked with @mjsabby and determined that LLVMSharp was previously going through some steps to produce its own `libllvm.dll` library here: https://github.com/microsoft/LLVMSharp/tree/master/tools/libLLVM

Namely, it was working around the fact that several methods such as `LLVMInitializeAllTargetInfos` are not proper exports and are instead inline functions.

I updated ClangSharp to recognize these functions (and other simple functions like them) and got LLVMSharp updated last night to begin using the C# generated equivalents instead: https://github.com/microsoft/LLVMSharp/pull/99.

This should ultimately allow LLVMSharp to use what a local build of `llvm` will produce natively.

**Comment by mjsabby** [comment] 2019-05-30 20:29
@tannergooding has it right. So this is an agility relief for me. I'll release LLVMSharp 8.0 final soon.

**Comment by cloudrex** [comment] 2019-05-31 00:28
should we change the version in the commit title?

**Comment by tannergooding** [comment] 2019-06-01 16:17
Just as an FYI, the `libLLVM` package (and likely the `libClang` package) could use some fixing before being published (and should be dependencies of the respective LLVMSharp and ClangSharp packages).

For example, It currently only has a targets file for net461, which results in warnings/errors when restoring for netcore or netstandard projects.

They also can't be recognized by native projects and can result in packing errors due to how they are copied to the output folder.

I'm working on building a nuspec that will generate a nuget package that will handle those scenarios and will update when complete.

**Comment by tannergooding** [comment] 2019-06-09 03:15
Going to close this as resolved now.

Both `libClang` and `libLLVM` have `8.0.0` packages available on NuGet. In both cases, these are small RID aware packages that reference 11 RID specific packages that contain the actual native assets (these are 11/12 of the platforms that LLVM natively distributes binaries for, minus PowerPC as that is not supported by .NET Core today).

The upside to this is you don't need to download a 272MB NuGet package and we can easily support a lot of RIDs. The downside is that you may have to specify a RuntimeIdentifier when building certain apps so that the `libclang` or `libLLVM` binary can be located by `DllImport` at runtime.

**Closed by tannergooding** 2019-06-09 03:15 UTC

**Comment by DaOnlyOwner** [comment] 2019-06-12 23:21
You should probably update the README so it specifies the correct version.

**Comment by yowl** [comment] 2019-06-24 14:28
I'm a bit confused.  Is there going to be a new nuget for LLVMSharp?
